// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRepairHistory(arg1:models.RepairHistory):Promise<void>;

export function CompleteRegister(arg1:string,arg2:string):Promise<string>;

export function CreateEquipment(arg1:models.Equipment):Promise<void>;

export function CreateMaintenance(arg1:models.MaintenanceSchedule):Promise<void>;

export function CreateSupplier(arg1:models.Supplier):Promise<void>;

export function DeleteEquipment(arg1:number):Promise<void>;

export function DeleteMaintenance(arg1:number):Promise<void>;

export function DeleteRepairHistory(arg1:number):Promise<void>;

export function DeleteSupplier(arg1:number):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetAllEquipment():Promise<Array<models.Equipment>>;

export function GetAllMaintenances():Promise<Array<models.MaintenanceSchedule>>;

export function GetAllRepairHistories():Promise<Array<models.RepairHistory>>;

export function GetAllSuppliers():Promise<Array<models.Supplier>>;

export function GetAllUsers():Promise<Array<models.User>>;

export function GetEquipmentDetail(arg1:number):Promise<models.Equipment>;

export function GetMaintenanceDetail(arg1:number):Promise<models.MaintenanceSchedule>;

export function GetRepairByMaintenance(arg1:number):Promise<Array<models.RepairHistory>>;

export function GetRepairHistoryByMaintenance(arg1:number):Promise<Array<models.RepairHistory>>;

export function GetSearchDetail(arg1:string,arg2:number):Promise<any>;

export function GetSupplierByID(arg1:number):Promise<models.Supplier>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<void>;

export function RegisterUser(arg1:models.User):Promise<string>;

export function SearchAll(arg1:string):Promise<Array<models.SearchResult>>;

export function UpdateEquipment(arg1:number,arg2:models.Equipment):Promise<void>;

export function UpdateMaintenance(arg1:number,arg2:models.MaintenanceSchedule):Promise<void>;

export function UpdateRepairHistory(arg1:number,arg2:models.RepairHistory):Promise<void>;

export function UpdateSupplier(arg1:models.Supplier):Promise<void>;

export function UpdateUser(arg1:models.User):Promise<void>;
