// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepairHistory(arg1) {
  return window['go']['main']['App']['AddRepairHistory'](arg1);
}

export function CompleteRegister(arg1, arg2) {
  return window['go']['main']['App']['CompleteRegister'](arg1, arg2);
}

export function CreateEquipment(arg1) {
  return window['go']['main']['App']['CreateEquipment'](arg1);
}

export function CreateMaintenance(arg1) {
  return window['go']['main']['App']['CreateMaintenance'](arg1);
}

export function CreateSupplier(arg1) {
  return window['go']['main']['App']['CreateSupplier'](arg1);
}

export function DeleteEquipment(arg1) {
  return window['go']['main']['App']['DeleteEquipment'](arg1);
}

export function DeleteMaintenance(arg1) {
  return window['go']['main']['App']['DeleteMaintenance'](arg1);
}

export function DeleteRepairHistory(arg1) {
  return window['go']['main']['App']['DeleteRepairHistory'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['main']['App']['DeleteSupplier'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetAllEquipment() {
  return window['go']['main']['App']['GetAllEquipment']();
}

export function GetAllMaintenances() {
  return window['go']['main']['App']['GetAllMaintenances']();
}

export function GetAllRepairHistories() {
  return window['go']['main']['App']['GetAllRepairHistories']();
}

export function GetAllSuppliers() {
  return window['go']['main']['App']['GetAllSuppliers']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetEquipmentDetail(arg1) {
  return window['go']['main']['App']['GetEquipmentDetail'](arg1);
}

export function GetMaintenanceDetail(arg1) {
  return window['go']['main']['App']['GetMaintenanceDetail'](arg1);
}

export function GetRepairByMaintenance(arg1) {
  return window['go']['main']['App']['GetRepairByMaintenance'](arg1);
}

export function GetRepairHistoryByMaintenance(arg1) {
  return window['go']['main']['App']['GetRepairHistoryByMaintenance'](arg1);
}

export function GetSearchDetail(arg1, arg2) {
  return window['go']['main']['App']['GetSearchDetail'](arg1, arg2);
}

export function GetSupplierByID(arg1) {
  return window['go']['main']['App']['GetSupplierByID'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RegisterUser(arg1) {
  return window['go']['main']['App']['RegisterUser'](arg1);
}

export function SearchAll(arg1) {
  return window['go']['main']['App']['SearchAll'](arg1);
}

export function UpdateEquipment(arg1, arg2) {
  return window['go']['main']['App']['UpdateEquipment'](arg1, arg2);
}

export function UpdateMaintenance(arg1, arg2) {
  return window['go']['main']['App']['UpdateMaintenance'](arg1, arg2);
}

export function UpdateRepairHistory(arg1, arg2) {
  return window['go']['main']['App']['UpdateRepairHistory'](arg1, arg2);
}

export function UpdateSupplier(arg1) {
  return window['go']['main']['App']['UpdateSupplier'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['main']['App']['UpdateUser'](arg1);
}
